"""Pipeline stage 6: mirror what the backend reads to the private Supabase bucket.

Uploads only an allowlist, built from the index itself:
  content/index.json, content/embeddings.npy, content/manifest.json
  content/info_index.json, content/info_embeddings.npy (Canvas course info, when built)
  slides/<course>/s<NN>/<slide_id>.webp and <slide_id>-thumb.webp, for indexed slides only
  slides/<course>/s<NN>/<slide_id>.boxes.json, the slide's word boxes (read-along), when built
  clips/<slide_id>.mp4 for indexed slides that have a clip, and clips/manifest.json (those rows only)
  topics/topics.json and the audio/<voice_id>/<hash>.mp3 files it points to, with each mp3's
  <hash>.words.json word timings (read-along) when there is one

Never uploaded, whatever is in _build/: transcripts, alignment, review files,
rosters, notebooks and code JSON, slides.json / deck.json, source_converted.pdf,
or anything under a `_private` folder. Every path is checked against the
allowlist and a denylist before it is sent.

Before anything is sent, every text object goes through the roster leak check
(indexer/leakcheck.py). One hit aborts the whole upload; the output names the
object and record, never the text. Without the rosters the upload refuses to run.

Unchanged objects are skipped: `content/upload_state.json` in the bucket holds
the sha256 of every object this script uploaded (each object also carries its
sha256 in its metadata). Objects from an earlier upload that are no longer in
the plan (for example a slide newly flagged for student names) are deleted.
After a successful upload, `settings.index_version` is set to the index's
version, and warm backends reload within a minute.

Run from the repo root:
  uv run --no-project --with-requirements requirements.txt python -m indexer.upload --dry-run
  uv run --no-project --with-requirements requirements.txt python -m indexer.upload
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx
import numpy as np

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from indexer import common  # noqa: E402
from indexer.leakcheck import Hits, RosterChecker, RosterMissing  # noqa: E402

STATE_PATH = "content/upload_state.json"
MAX_OBJECT_BYTES = 50 * 1024**2  # Supabase free plan per-file limit
WORKERS = 8
EXIT_OK, EXIT_PLAN, EXIT_LEAK, EXIT_UPLOAD, EXIT_CONFIG = 0, 2, 4, 5, 6

ALLOWED = [
    re.compile(r"^content/(index\.json|embeddings\.npy|manifest\.json|info_index\.json|info_embeddings\.npy)$"),
    re.compile(r"^slides/\d{5}/s\d{2}/\d{5}-s\d{2}-\d{3}(-thumb)?\.webp$"),
    re.compile(r"^slides/\d{5}/s\d{2}/\d{5}-s\d{2}-\d{3}\.boxes\.json$"),
    re.compile(r"^clips/\d{5}-s\d{2}-\d{3}\.mp4$"),
    re.compile(r"^clips/manifest\.json$"),
    re.compile(r"^topics/topics\.json$"),
    re.compile(r"^audio/[A-Za-z0-9_\-]{1,100}/[A-Za-z0-9_\-]{1,100}\.mp3$"),
    re.compile(r"^audio/[A-Za-z0-9_\-]{1,100}/[A-Za-z0-9_\-]{1,100}\.words\.json$"),
]
CLIP_FIELDS = ("slide_id", "course", "session", "start", "end", "duration", "reason_kept")
# Never uploaded, even if a path would otherwise match the allowlist (belt and braces).
FORBIDDEN_DIRS = {
    "transcripts", "align", "review", "overrides", "inbox", "code", "logs", "qa", "embed_cache", "versions",
}
FORBIDDEN_NAMES = {"slides.json", "deck.json", "source_converted.pdf", "missing.json", "summary.json", "rejected.json"}
FORBIDDEN_SUFFIXES = {".meta.json", ".vtt", ".pdf", ".pptx", ".csv", ".md", ".txt", ".ipynb", ".jsonl", ".srt", ".xlsx"}
CONTENT_TYPES = {
    ".json": "application/json",
    ".npy": "application/octet-stream",
    ".webp": "image/webp",
    ".mp4": "video/mp4",
    ".mp3": "audio/mpeg",
}


def forbidden(path: str) -> bool:
    """True for anything that must never leave the build machine, whatever the allowlist says."""
    parts = path.replace("\\", "/").lower().split("/")
    name = parts[-1]
    if any(p.startswith("_private") or p.startswith(".") or p == ".." or "roster" in p for p in parts):
        return True
    if parts[0] in FORBIDDEN_DIRS or any(p in FORBIDDEN_DIRS for p in parts[:-1]):
        return True
    return name in FORBIDDEN_NAMES or any(name.endswith(s) for s in FORBIDDEN_SUFFIXES)


def allowed(path: str) -> bool:
    """True when a bucket path is on the allowlist and not forbidden (both checks, always)."""
    return not forbidden(path) and any(rx.match(path) for rx in ALLOWED)


class PlanError(RuntimeError):
    """The build is not in a state that may be uploaded (missing, mismatched, or not allowed)."""


@dataclass
class Item:
    """One object to upload: generated bytes, or a local file read only when needed."""

    path: str  # bucket path
    src: Path | None = None
    blob: bytes | None = None
    _sha: str | None = None

    @property
    def data(self) -> bytes:
        return self.blob if self.blob is not None else self.src.read_bytes()  # type: ignore[union-attr]

    @property
    def size(self) -> int:
        return len(self.blob) if self.blob is not None else self.src.stat().st_size  # type: ignore[union-attr]

    @property
    def sha256(self) -> str:
        if self._sha is None:
            self._sha = (common.sha256_bytes(self.blob) if self.blob is not None
                         else common.sha256_file(self.src))  # type: ignore[arg-type]
        return self._sha

    @property
    def content_type(self) -> str:
        return CONTENT_TYPES.get(Path(self.path).suffix, "application/octet-stream")

    @property
    def is_text(self) -> bool:
        return self.path.endswith(".json")

    @property
    def cache_seconds(self) -> int:
        # Index files change in place on every upload, so browsers and the CDN may keep them a minute only.
        return 60 if self.is_text or self.path.endswith(".npy") else 3600


# ---------------------------------------------------------------- the plan

class _Plan:
    """Collects the objects to upload, refusing any path that is not allowed or too large."""

    def __init__(self, build: Path) -> None:
        self.build = build
        self.items: dict[str, Item] = {}

    def add(self, path: str, data: bytes | None = None, src: Path | None = None) -> None:
        """Add generated bytes or a file at a bucket path, after the allowlist and size checks."""
        if not allowed(path):
            raise PlanError(f"refusing to upload {path}: not on the allowlist")
        item = Item(path, src=src, blob=data)
        if item.size > MAX_OBJECT_BYTES:
            raise PlanError(f"{path} is {item.size / 1e6:.1f} MB, over the 50 MB per-file limit")
        self.items[path] = item

    def add_file(self, path: str) -> None:
        """Add a build output by its relative path (forbidden paths are refused)."""
        path = path.lstrip("/")
        if forbidden(path):
            raise PlanError(f"refusing to upload {path}: forbidden path")
        src = self.build / path
        if not src.is_file():
            raise PlanError(f"missing build output: {path}")
        self.add(path, src=src)


def _check_slide_index(content: Path) -> tuple[dict[str, Any], bytes, bytes, list[dict[str, Any]]]:
    """(manifest, index bytes, embeddings bytes, records), after checking they belong together."""
    manifest = common.read_json(content / "manifest.json")
    index_bytes = _read(content / "index.json")
    emb_bytes = _read(content / "embeddings.npy")
    if not manifest or manifest.get("embeddings") != "complete":
        raise PlanError("The index has no embeddings yet. Run indexer/build_index.py with VOYAGE_API_KEY set first.")
    index = json.loads(index_bytes)
    records = index.get("records", []) if isinstance(index, dict) else index
    rows = np.load(io.BytesIO(emb_bytes), allow_pickle=False).shape[0]
    if rows != len(records):
        raise PlanError(f"embeddings.npy has {rows} rows but index.json has {len(records)} records. "
                        "Re-run build_index.")
    if isinstance(index, dict) and index.get("index_version") != manifest.get("index_version"):
        raise PlanError("index.json and manifest.json are from different builds. Re-run build_index.")
    return manifest, index_bytes, emb_bytes, records


def _add_media(plan: _Plan, records: list[dict[str, Any]]) -> None:
    """Slide images and clips for indexed slides, and only the manifest rows of uploaded clips."""
    clip_ids = set()
    for rec in records:
        if rec.get("kind", "slide") != "slide":
            continue
        for key in ("image", "thumb"):
            if rec.get(key):
                plan.add_file(rec[key])
        boxes = boxes_for(rec.get("image"))
        if boxes and (plan.build / boxes).is_file():  # word boxes are optional (read-along highlights)
            plan.add_file(boxes)
        if rec.get("clip"):
            plan.add_file(rec["clip"])
            clip_ids.add(rec["id"])
    # Only the rows for uploaded clips, and only the fields the backend reads (no local source paths).
    manifest_path = plan.build / "clips" / "manifest.json"
    rows_kept = [
        {k: r[k] for k in CLIP_FIELDS if k in r}
        for r in (common.read_json(manifest_path, []) or [])
        if r.get("slide_id") in clip_ids
    ]
    if rows_kept or manifest_path.exists():
        plan.add("clips/manifest.json", common.dump_json(rows_kept))


def _add_topics(plan: _Plan) -> None:
    """The suggested questions and the stored mp3s their playlists point to."""
    topics_path = plan.build / "topics" / "topics.json"
    if not topics_path.exists():
        return
    topics = json.loads(_read(topics_path))
    plan.add("topics/topics.json", common.dump_json(topics))
    for t in topics if isinstance(topics, list) else []:
        for seg in ((t or {}).get("playlist") or {}).get("segments", []):
            if seg.get("audio_path"):
                plan.add_file(seg["audio_path"])
                words = words_for(seg["audio_path"])
                if words and (plan.build / words).is_file():  # word timings are optional
                    plan.add_file(words)


def plan(build: Path) -> tuple[list[Item], dict[str, Any]]:
    """Everything to upload, read from the index. Raises PlanError if the build is not uploadable."""
    content = build / "content"
    manifest, index_bytes, emb_bytes, records = _check_slide_index(content)
    p = _Plan(build)
    _add_media(p, records)
    _add_topics(p)
    info = info_files(content)
    for path, data in info:
        p.add(path, data)
    p.add("content/embeddings.npy", emb_bytes)
    p.add("content/index.json", index_bytes)
    p.add("content/manifest.json", common.dump_json(manifest))
    order = {"slides": 0, "clips": 1, "audio": 2, "topics": 3}
    ordered = sorted(p.items.values(), key=lambda it: (order.get(it.path.split("/")[0], 4), it.path))
    # Index files last, manifest very last: a reader never sees an index whose images are missing.
    tail = [path for path, _ in info] + ["content/embeddings.npy", "content/index.json", "content/manifest.json"]
    ordered = [it for it in ordered if it.path not in tail] + [p.items[path] for path in tail]
    if info:
        # The backend reloads when settings.index_version changes, so a new course-info index
        # (with an unchanged slide index) still gets picked up.
        info_hash = common.sha256_bytes(info[1][1])[:8]
        manifest = {**manifest, "index_version": f"{manifest['index_version']}+info-{info_hash}"}
    return ordered, manifest


def boxes_for(image: str | None) -> str | None:
    """`slides/.../<slide_id>.webp` -> its word-box sidecar `slides/.../<slide_id>.boxes.json`."""
    image = str(image or "").lstrip("/")
    return image[: -len(".webp")] + ".boxes.json" if image.endswith(".webp") else None


def words_for(audio_path: str | None) -> str | None:
    """`audio/<tag>/<hash>.mp3` -> its word timings `audio/<tag>/<hash>.words.json`."""
    path = str(audio_path or "").lstrip("/")
    return path[: -len(".mp3")] + ".words.json" if path.endswith(".mp3") else None


def info_files(content: Path) -> list[tuple[str, bytes]]:
    """The Canvas course-info index (indexer/build_info_index.py), when it exists and is complete."""
    index_path = content / "info_index.json"
    if not index_path.exists():
        return []
    emb_bytes = _read(content / "info_embeddings.npy")
    index_bytes = _read(index_path)
    index = json.loads(index_bytes)
    records = index.get("records", []) if isinstance(index, dict) else index
    shape = np.load(io.BytesIO(emb_bytes), allow_pickle=False).shape
    if shape[0] != len(records):
        raise PlanError(f"info_embeddings.npy has {shape[0]} rows but info_index.json has {len(records)} records. "
                        "Re-run build_info_index.")
    dim = (common.read_json(content / "manifest.json", {}) or {}).get("embedding_dim")
    if dim and len(shape) == 2 and shape[1] != dim:
        raise PlanError(f"info_embeddings.npy has dimension {shape[1]}, the slide index {dim}. "
                        "Re-run build_info_index.")
    return [("content/info_embeddings.npy", emb_bytes), ("content/info_index.json", index_bytes)]


def _read(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise PlanError(f"missing build output: {path.name} ({type(exc).__name__})") from exc


def leak_check(items: list[Item], checker: RosterChecker) -> Hits:
    """The roster leak check over every text object in the plan."""
    hits = Hits()
    for it in items:
        if it.is_text:
            checker.check_object(it.path, it.data, hits)
    return hits


# ---------------------------------------------------------------- upload

def remote_state(sb: common.Supabase | None) -> dict[str, dict[str, Any]] | None:
    """{path: {sha256, size}} from the last upload; {} when there is none, None without Supabase."""
    if sb is None:
        return None
    raw = sb.download(STATE_PATH)
    if not raw:
        return {}
    try:
        data = json.loads(raw)
        return data.get("objects", {}) if isinstance(data, dict) else {}
    except ValueError:
        return {}  # a corrupt state file only means every object is sent again


def run(
    build: Path,
    roster: Path,
    sb: common.Supabase | None,
    dry_run: bool = False,
    force: bool = False,
    prune: bool = True,
    log: Callable[[str], None] = print,
    only: tuple[str, ...] = (),
) -> int:
    """Plan, leak-check, then upload what changed, prune what left the index, and bump the version.

    `only` (bucket path prefixes, e.g. ("slides/", "audio/")) limits the run to those objects:
    nothing else is checked, sent or deleted, and settings.index_version is left alone.
    """
    try:
        items, manifest = plan(build)
    except PlanError as exc:
        log(f"Upload stopped: {exc}")
        return EXIT_PLAN
    if only:
        items = [it for it in items if it.path.startswith(only)]
        prune = False
        log(f"Only objects under {', '.join(only)}: {len(items)} in the plan; the index version is not changed.")
    hits = _leak_hits(items, roster, log)
    if hits is None:
        return EXIT_LEAK
    if hits.total and not dry_run:
        log("Upload aborted: fix the de-identification for the places above and rebuild. Nothing was uploaded.")
        return EXIT_LEAK

    try:
        state = remote_state(sb)
    except common.SupabaseError as exc:
        log(f"Upload stopped: could not read the bucket ({exc}). "
            f"Check SUPABASE_URL and that bucket {sb.bucket if sb else ''} exists.")
        return EXIT_CONFIG
    known = state or {}
    todo, stale = _changes(items, known, force, prune)
    version = manifest["index_version"]
    if dry_run:
        _report_dry_run(items, todo, stale, known, state is None, None if only else version, log)
        if hits.total:
            log("BLOCKED: the real upload would stop at the leak check above. Fix those places and rebuild first.")
            return EXIT_LEAK
        return EXIT_OK
    if sb is None:
        log("Upload stopped: Supabase is not configured (SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY in .env).")
        return EXIT_CONFIG
    return _upload(sb, items, todo, stale, known, version, not only, log)


def _changes(items: list[Item], known: dict[str, Any], force: bool, prune: bool) -> tuple[list[Item], list[str]]:
    """(objects to send, bucket paths to delete) compared with the last upload's state.

    `force` sends every object; with `prune`, an allowed bucket path that left the plan is deleted.
    """
    todo = [it for it in items if force or known.get(it.path, {}).get("sha256") != it.sha256]
    planned = {it.path for it in items}
    stale = sorted(p for p in known if p not in planned and allowed(p)) if prune else []
    return todo, stale


def _leak_hits(items: list[Item], roster: Path, log: Callable[[str], None]) -> Hits | None:
    """Run the roster leak check over the plan and log its summary; None (after saying why) without rosters."""
    try:
        checker = RosterChecker.from_dir(roster)
    except RosterMissing as exc:
        log(f"Upload stopped: {exc}. The leak check is the gate; nothing was uploaded.")
        return None
    hits = leak_check(items, checker)
    log(hits.summary())
    return hits


def _upload(sb: common.Supabase, items: list[Item], todo: list[Item], stale: list[str], known: dict[str, Any],
            version: str, set_version: bool, log: Callable[[str], None]) -> int:
    """Send the changed objects, prune the stale ones, save the state, then set settings.index_version.

    `set_version` is False for an `--only` run, which leaves settings.index_version alone.
    """
    total = sum(it.size for it in todo)
    log(f"Uploading {len(todo)} of {len(items)} objects ({total / 1e6:.1f} MB) to bucket {sb.bucket}")
    new_state = dict(known)
    failed = _send_objects(sb, todo, new_state, log)
    if not failed and stale:
        _prune(sb, stale, new_state, log)
    _save_state(sb, version, new_state, log)
    if failed:
        log(f"Upload incomplete: {len(failed)} objects failed. Re-run the same command; finished objects are skipped.")
        return EXIT_UPLOAD
    if not set_version:
        log("Done. The index was not part of this run, so settings.index_version is unchanged.")
        return EXIT_OK
    try:
        sb.upsert("settings", [{"key": "index_version", "value": version}], on="key")
    except common.SupabaseError as exc:
        log(f"Uploaded, but setting settings.index_version failed: {exc}. Re-run to retry.")
        return EXIT_UPLOAD
    log(f"Done. settings.index_version = {version}. Warm backends reload within a minute.")
    return EXIT_OK


def _report_dry_run(items: list[Item], todo: list[Item], stale: list[str], known: dict[str, Any],
                    state_unknown: bool, version: str | None, log: Callable[[str], None]) -> None:
    """List what an upload would send and delete, with sizes per top-level folder. Sends nothing.

    `version` is None for an `--only` run, which leaves settings.index_version alone.
    """
    label = ("remote state unknown (Supabase not configured), so every object is listed" if state_unknown
             else "compared with the bucket")
    log(f"Dry run for index {version or 'unchanged'}: {label}.")
    for it in todo:
        status = "new" if it.path not in known else "changed"
        log(f"  {status:8} {it.size:>12,d}  {it.path}")
    for p in stale:
        log(f"  {'delete':8} {'':>12}  {p}")
    by_top: dict[str, list[int]] = {}
    for it in items:
        top = it.path.split("/")[0]
        by_top.setdefault(top, [0, 0])
        by_top[top][0] += 1
        by_top[top][1] += it.size
    for top, (n, b) in sorted(by_top.items()):
        log(f"  {top + '/':10} {n:>5} objects  {b / 1e6:8.1f} MB")
    after = sum(it.size for it in items) / 1e6
    log(f"  {'total':10} {len(items):>5} objects  {after:8.1f} MB in the bucket after this upload")
    total = sum(it.size for it in todo)
    log(
        f"Would upload {len(todo)} of {len(items)} objects ({total / 1e6:.1f} MB), "
        f"skip {len(items) - len(todo)} unchanged, delete {len(stale)}"
        + (f", then set settings.index_version = {version}." if version else ".")
    )


def _send_objects(sb: common.Supabase, todo: list[Item], new_state: dict[str, Any],
                  log: Callable[[str], None]) -> list[str]:
    """Upload media in parallel, then the index files in order. Returns the paths that failed.

    The index files go only after every media object landed, so the live index never points
    at an image or clip that is not in the bucket yet.
    """
    failed: list[str] = []
    media = [it for it in todo if not it.path.startswith("content/")]
    tail = [it for it in todo if it.path.startswith("content/")]

    def send(it: Item) -> None:
        sb.upload(it.path, it.data, it.content_type, it.sha256, it.cache_seconds)

    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {pool.submit(send, it): it for it in media}
        for n, fut in enumerate(as_completed(futures), 1):
            it = futures[fut]
            try:
                fut.result()
                new_state[it.path] = {"sha256": it.sha256, "size": it.size}
            except common.SupabaseError as exc:
                failed.append(it.path)
                log(f"  failed {it.path}: {exc}")
            if n % 200 == 0:
                log(f"  {n}/{len(media)} media objects")
    if not failed:
        for it in tail:  # in order: embeddings, index, manifest
            try:
                send(it)
                new_state[it.path] = {"sha256": it.sha256, "size": it.size}
            except common.SupabaseError as exc:
                failed.append(it.path)
                log(f"  failed {it.path}: {exc}")
                break
    return failed


def _prune(sb: common.Supabase, stale: list[str], new_state: dict[str, Any], log: Callable[[str], None]) -> None:
    """Delete objects from an earlier upload that are no longer in the index (a newly flagged slide, say)."""
    try:
        sb.delete(stale)
        for p in stale:
            new_state.pop(p, None)
        log(f"Deleted {len(stale)} objects that are no longer in the index")
    except common.SupabaseError as exc:
        log(f"  could not delete old objects: {exc}")


def _save_state(sb: common.Supabase, version: str, new_state: dict[str, Any], log: Callable[[str], None]) -> None:
    """Record what is in the bucket, so the next run skips unchanged objects."""
    try:
        state_bytes = common.dump_json({"index_version": version, "objects": dict(sorted(new_state.items()))})
        sb.upload(STATE_PATH, state_bytes, "application/json", common.sha256_bytes(state_bytes), 60)
    except common.SupabaseError as exc:
        log(f"  could not save the upload state (next run re-uploads everything): {exc}")


def main(argv: list[str] | None = None, client: httpx.Client | None = None) -> int:
    """Command line: mirror the build to the private bucket, or list what would change with --dry-run.

    Without Supabase settings in .env the run can still plan and leak-check (a dry run lists everything).
    """
    ap =argparse.ArgumentParser(description="Mirror build outputs to the private Supabase bucket")
    ap.add_argument("--archive", help="Lecture Archive folder (default ~/Lecture Archive or $LECTURE_ARCHIVE)")
    ap.add_argument("--build", help="build folder (default <archive>/_build)")
    ap.add_argument("--roster", help="roster folder (default <archive>/_private/rosters)")
    ap.add_argument("--dry-run", action="store_true", help="list what would upload, with sizes; send nothing")
    ap.add_argument("--force", action="store_true", help="re-upload every object even if unchanged")
    ap.add_argument("--no-prune", action="store_true", help="keep objects that are no longer in the index")
    ap.add_argument("--only", action="append", default=[], metavar="PREFIX",
                    help="only objects under this bucket prefix (repeatable, e.g. --only slides/ --only audio/); "
                         "no pruning and no index version change")
    a = ap.parse_args(argv)
    common.load_env()
    archive = common.archive_dir(a.archive)
    build = Path(a.build).expanduser() if a.build else common.build_dir(archive)
    roster = Path(a.roster).expanduser() if a.roster else common.roster_dir(archive)
    sb = common.Supabase(client=client) if common.Supabase.configured() else None
    return run(build, roster, sb, dry_run=a.dry_run, force=a.force, prune=not a.no_prune, only=tuple(a.only))


if __name__ == "__main__":
    sys.exit(main())
