"""Pipeline stage 6: mirror what the backend reads to the private Supabase bucket.

Uploads only an allowlist, built from the index itself:
  content/index.json, content/embeddings.npy, content/manifest.json
  slides/<course>/s<NN>/<slide_id>.webp and <slide_id>-thumb.webp, for indexed slides only
  clips/<slide_id>.mp4 for indexed slides that have a clip, and clips/manifest.json (those rows only)
  topics/topics.json and the audio/<voice_id>/<hash>.mp3 files it points to

Never uploaded, whatever is in _build/: transcripts, alignment, review files,
rosters, notebooks and code JSON, slides.json / deck.json, source_converted.pdf,
or anything under a `_private` folder. Every path is checked against the
allowlist and a denylist before it is sent.

Before anything is sent, every text object goes through the roster leak check
(indexer/leakcheck.py). One hit aborts the whole upload; the output names the
object and record, never the text. Without the rosters the upload refuses to run.

Unchanged objects are skipped: `content/upload_state.json` in the bucket holds
the sha256 of every object this script uploaded (each object also carries its
sha256 in its metadata). Objects from an earlier upload that are no longer in
the plan (for example a slide newly flagged for student names) are deleted.
After a successful upload, `settings.index_version` is set to the index's
version, and warm backends reload within a minute.

Run from the repo root:
  uv run --no-project --with-requirements requirements.txt python -m indexer.upload --dry-run
  uv run --no-project --with-requirements requirements.txt python -m indexer.upload
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import httpx
import numpy as np

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from indexer import common  # noqa: E402
from indexer.leakcheck import Hits, RosterChecker, RosterMissing  # noqa: E402

STATE_PATH = "content/upload_state.json"
MAX_OBJECT_BYTES = 50 * 1024**2  # Supabase free plan per-file limit
WORKERS = 8
EXIT_OK, EXIT_PLAN, EXIT_LEAK, EXIT_UPLOAD, EXIT_CONFIG = 0, 2, 4, 5, 6

ALLOWED = [
    re.compile(r"^content/(index\.json|embeddings\.npy|manifest\.json)$"),
    re.compile(r"^slides/\d{5}/s\d{2}/\d{5}-s\d{2}-\d{3}(-thumb)?\.webp$"),
    re.compile(r"^clips/\d{5}-s\d{2}-\d{3}\.mp4$"),
    re.compile(r"^clips/manifest\.json$"),
    re.compile(r"^topics/topics\.json$"),
    re.compile(r"^audio/[A-Za-z0-9_\-]{1,100}/[A-Za-z0-9_\-]{1,100}\.mp3$"),
]
CLIP_FIELDS = ("slide_id", "course", "session", "start", "end", "duration", "reason_kept")
FORBIDDEN_DIRS = {"transcripts", "align", "review", "overrides", "inbox", "code", "logs", "qa", "embed_cache", "versions"}
FORBIDDEN_NAMES = {"slides.json", "deck.json", "source_converted.pdf", "missing.json", "summary.json", "rejected.json"}
FORBIDDEN_SUFFIXES = {".meta.json", ".vtt", ".pdf", ".pptx", ".csv", ".md", ".txt", ".ipynb", ".jsonl", ".srt", ".xlsx"}
CONTENT_TYPES = {
    ".json": "application/json",
    ".npy": "application/octet-stream",
    ".webp": "image/webp",
    ".mp4": "video/mp4",
    ".mp3": "audio/mpeg",
}


def forbidden(path: str) -> bool:
    parts = path.replace("\\", "/").lower().split("/")
    name = parts[-1]
    if any(p.startswith("_private") or p.startswith(".") or p == ".." or "roster" in p for p in parts):
        return True
    if parts[0] in FORBIDDEN_DIRS or any(p in FORBIDDEN_DIRS for p in parts[:-1]):
        return True
    return name in FORBIDDEN_NAMES or any(name.endswith(s) for s in FORBIDDEN_SUFFIXES)


def allowed(path: str) -> bool:
    return not forbidden(path) and any(rx.match(path) for rx in ALLOWED)


class PlanError(RuntimeError):
    pass


@dataclass
class Item:
    """One object to upload: generated bytes, or a local file read only when needed."""

    path: str  # bucket path
    src: Path | None = None
    blob: bytes | None = None
    _sha: str | None = None

    @property
    def data(self) -> bytes:
        return self.blob if self.blob is not None else self.src.read_bytes()  # type: ignore[union-attr]

    @property
    def size(self) -> int:
        return len(self.blob) if self.blob is not None else self.src.stat().st_size  # type: ignore[union-attr]

    @property
    def sha256(self) -> str:
        if self._sha is None:
            self._sha = common.sha256_bytes(self.blob) if self.blob is not None else common.sha256_file(self.src)  # type: ignore[arg-type]
        return self._sha

    @property
    def content_type(self) -> str:
        return CONTENT_TYPES.get(Path(self.path).suffix, "application/octet-stream")

    @property
    def is_text(self) -> bool:
        return self.path.endswith(".json")

    @property
    def cache_seconds(self) -> int:
        return 60 if self.is_text or self.path.endswith(".npy") else 3600


# ---------------------------------------------------------------- the plan

def plan(build: Path) -> tuple[list[Item], dict[str, Any]]:
    """Everything to upload, read from the index. Raises PlanError if the build is not uploadable."""
    content = build / "content"
    manifest = common.read_json(content / "manifest.json")
    index_bytes = _read(content / "index.json")
    emb_bytes = _read(content / "embeddings.npy")
    if not manifest or manifest.get("embeddings") != "complete":
        raise PlanError("The index has no embeddings yet. Run indexer/build_index.py with VOYAGE_API_KEY set first.")
    index = json.loads(index_bytes)
    records = index.get("records", []) if isinstance(index, dict) else index
    rows = np.load(io.BytesIO(emb_bytes), allow_pickle=False).shape[0]
    if rows != len(records):
        raise PlanError(f"embeddings.npy has {rows} rows but index.json has {len(records)} records. Re-run build_index.")
    if isinstance(index, dict) and index.get("index_version") != manifest.get("index_version"):
        raise PlanError("index.json and manifest.json are from different builds. Re-run build_index.")

    items: dict[str, Item] = {}

    def add(path: str, data: bytes | None = None, src: Path | None = None) -> None:
        if not allowed(path):
            raise PlanError(f"refusing to upload {path}: not on the allowlist")
        item = Item(path, src=src, blob=data)
        if item.size > MAX_OBJECT_BYTES:
            raise PlanError(f"{path} is {item.size / 1e6:.1f} MB, over the 50 MB per-file limit")
        items[path] = item

    def add_file(path: str) -> None:
        path = path.lstrip("/")
        if forbidden(path):
            raise PlanError(f"refusing to upload {path}: forbidden path")
        src = build / path
        if not src.is_file():
            raise PlanError(f"missing build output: {path}")
        add(path, src=src)

    clip_ids = set()
    for rec in records:
        if rec.get("kind", "slide") != "slide":
            continue
        for key in ("image", "thumb"):
            if rec.get(key):
                add_file(rec[key])
        if rec.get("clip"):
            add_file(rec["clip"])
            clip_ids.add(rec["id"])
    # Only the rows for uploaded clips, and only the fields the backend reads (no local source paths).
    rows_kept = [
        {k: r[k] for k in CLIP_FIELDS if k in r}
        for r in (common.read_json(build / "clips" / "manifest.json", []) or [])
        if r.get("slide_id") in clip_ids
    ]
    if rows_kept or (build / "clips" / "manifest.json").exists():
        add("clips/manifest.json", common.dump_json(rows_kept))

    topics_path = build / "topics" / "topics.json"
    if topics_path.exists():
        topics = json.loads(_read(topics_path))
        add("topics/topics.json", common.dump_json(topics))
        for t in topics if isinstance(topics, list) else []:
            for seg in ((t or {}).get("playlist") or {}).get("segments", []):
                if seg.get("audio_path"):
                    add_file(seg["audio_path"])

    add("content/embeddings.npy", emb_bytes)
    add("content/index.json", index_bytes)
    add("content/manifest.json", common.dump_json(manifest))
    order = {"slides": 0, "clips": 1, "audio": 2, "topics": 3}
    ordered = sorted(items.values(), key=lambda it: (order.get(it.path.split("/")[0], 4), it.path))
    # Index files last, manifest very last: a reader never sees an index whose images are missing.
    tail = ["content/embeddings.npy", "content/index.json", "content/manifest.json"]
    ordered = [it for it in ordered if it.path not in tail] + [items[p] for p in tail]
    return ordered, manifest


def _read(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise PlanError(f"missing build output: {path.name} ({type(exc).__name__})") from exc


def leak_check(items: list[Item], checker: RosterChecker) -> Hits:
    hits = Hits()
    for it in items:
        if it.is_text:
            checker.check_object(it.path, it.data, hits)
    return hits


# ---------------------------------------------------------------- upload

def remote_state(sb: common.Supabase | None) -> dict[str, dict[str, Any]] | None:
    if sb is None:
        return None
    raw = sb.download(STATE_PATH)
    if not raw:
        return {}
    try:
        data = json.loads(raw)
        return data.get("objects", {}) if isinstance(data, dict) else {}
    except ValueError:
        return {}


def run(
    build: Path,
    roster: Path,
    sb: common.Supabase | None,
    dry_run: bool = False,
    force: bool = False,
    prune: bool = True,
    log: Callable[[str], None] = print,
) -> int:
    try:
        items, manifest = plan(build)
    except PlanError as exc:
        log(f"Upload stopped: {exc}")
        return EXIT_PLAN
    try:
        checker = RosterChecker.from_dir(roster)
    except RosterMissing as exc:
        log(f"Upload stopped: {exc}. The leak check is the gate; nothing was uploaded.")
        return EXIT_LEAK
    hits = leak_check(items, checker)
    log(hits.summary())
    if hits.total and not dry_run:
        log("Upload aborted: fix the de-identification for the places above and rebuild. Nothing was uploaded.")
        return EXIT_LEAK

    try:
        state = remote_state(sb)
    except common.SupabaseError as exc:
        log(f"Upload stopped: could not read the bucket ({exc}). Check SUPABASE_URL and that bucket {sb.bucket if sb else ''} exists.")
        return EXIT_CONFIG
    known = state or {}
    todo = [it for it in items if force or known.get(it.path, {}).get("sha256") != it.sha256]
    planned = {it.path for it in items}
    stale = sorted(p for p in known if p not in planned and allowed(p)) if prune else []
    total = sum(it.size for it in todo)
    version = manifest["index_version"]

    if dry_run:
        label = "remote state unknown (Supabase not configured), so every object is listed" if state is None else "compared with the bucket"
        log(f"Dry run for index {version}: {label}.")
        for it in todo:
            status = "new" if it.path not in known else "changed"
            log(f"  {status:8} {it.size:>12,d}  {it.path}")
        for p in stale:
            log(f"  {'delete':8} {'':>12}  {p}")
        by_top: dict[str, list[int]] = {}
        for it in items:
            top = it.path.split("/")[0]
            by_top.setdefault(top, [0, 0])
            by_top[top][0] += 1
            by_top[top][1] += it.size
        for top, (n, b) in sorted(by_top.items()):
            log(f"  {top + '/':10} {n:>5} objects  {b / 1e6:8.1f} MB")
        log(f"  {'total':10} {len(items):>5} objects  {sum(it.size for it in items) / 1e6:8.1f} MB in the bucket after this upload")
        log(
            f"Would upload {len(todo)} of {len(items)} objects ({total / 1e6:.1f} MB), "
            f"skip {len(items) - len(todo)} unchanged, delete {len(stale)}, then set settings.index_version = {version}."
        )
        if hits.total:
            log("BLOCKED: the real upload would stop at the leak check above. Fix those places and rebuild first.")
            return EXIT_LEAK
        return EXIT_OK
    if sb is None:
        log("Upload stopped: Supabase is not configured (SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY in .env).")
        return EXIT_CONFIG

    log(f"Uploading {len(todo)} of {len(items)} objects ({total / 1e6:.1f} MB) to bucket {sb.bucket}")
    new_state = dict(known)
    failed: list[str] = []
    media = [it for it in todo if not it.path.startswith("content/")]
    tail = [it for it in todo if it.path.startswith("content/")]

    def send(it: Item) -> None:
        sb.upload(it.path, it.data, it.content_type, it.sha256, it.cache_seconds)

    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {pool.submit(send, it): it for it in media}
        for n, fut in enumerate(as_completed(futures), 1):
            it = futures[fut]
            try:
                fut.result()
                new_state[it.path] = {"sha256": it.sha256, "size": it.size}
            except common.SupabaseError as exc:
                failed.append(it.path)
                log(f"  failed {it.path}: {exc}")
            if n % 200 == 0:
                log(f"  {n}/{len(media)} media objects")
    if not failed:
        for it in tail:  # in order: embeddings, index, manifest
            try:
                send(it)
                new_state[it.path] = {"sha256": it.sha256, "size": it.size}
            except common.SupabaseError as exc:
                failed.append(it.path)
                log(f"  failed {it.path}: {exc}")
                break
    if not failed and stale:
        try:
            sb.delete(stale)
            for p in stale:
                new_state.pop(p, None)
            log(f"Deleted {len(stale)} objects that are no longer in the index")
        except common.SupabaseError as exc:
            log(f"  could not delete old objects: {exc}")
    try:
        state_bytes = common.dump_json({"index_version": version, "objects": dict(sorted(new_state.items()))})
        sb.upload(STATE_PATH, state_bytes, "application/json", common.sha256_bytes(state_bytes), 60)
    except common.SupabaseError as exc:
        log(f"  could not save the upload state (next run re-uploads everything): {exc}")
    if failed:
        log(f"Upload incomplete: {len(failed)} objects failed. Re-run the same command; finished objects are skipped.")
        return EXIT_UPLOAD
    try:
        sb.upsert("settings", [{"key": "index_version", "value": version}], on="key")
    except common.SupabaseError as exc:
        log(f"Uploaded, but setting settings.index_version failed: {exc}. Re-run to retry.")
        return EXIT_UPLOAD
    log(f"Done. settings.index_version = {version}. Warm backends reload within a minute.")
    return EXIT_OK


def main(argv: list[str] | None = None, client: httpx.Client | None = None) -> int:
    ap = argparse.ArgumentParser(description="Mirror build outputs to the private Supabase bucket")
    ap.add_argument("--archive", help="Lecture Archive folder (default ~/Lecture Archive or $LECTURE_ARCHIVE)")
    ap.add_argument("--build", help="build folder (default <archive>/_build)")
    ap.add_argument("--roster", help="roster folder (default <archive>/_private/rosters)")
    ap.add_argument("--dry-run", action="store_true", help="list what would upload, with sizes; send nothing")
    ap.add_argument("--force", action="store_true", help="re-upload every object even if unchanged")
    ap.add_argument("--no-prune", action="store_true", help="keep objects that are no longer in the index")
    a = ap.parse_args(argv)
    common.load_env()
    archive = common.archive_dir(a.archive)
    build = Path(a.build).expanduser() if a.build else common.build_dir(archive)
    roster = Path(a.roster).expanduser() if a.roster else common.roster_dir(archive)
    sb = common.Supabase(client=client) if common.Supabase.configured() else None
    return run(build, roster, sb, dry_run=a.dry_run, force=a.force, prune=not a.no_prune)


if __name__ == "__main__":
    sys.exit(main())
