"""Course FAQ answers: logistics questions get Ben's own written answer, a link, or the TA's contact card.

The first real-question eval (evals/README.md, Oct 7) showed most student email
is logistics. Ben's course FAQs already answer most of it in his words, so
`/api/ask` checks the FAQ first, before slide retrieval (docs/SPEC.md, "Inside
/api/ask", step 3a): an FAQ hit costs no embedding and no model call.

- Entries live in app/faq_entries.json: patterns (regular expressions, matched
  case-insensitively unless an entry says otherwise), Ben's answer per course
  ("all", "70445", "45884"), optional link buttons, and whether to show the
  TA contact card. The first entry whose pattern matches wins, so specific
  entries come first.
- An entry with answers only for one course answers only when the student's
  course filter is that course or "All courses" (then labelled with the course).
- TA names and emails are not in the repo. They come from the TA_CONTACTS
  environment variable, JSON like {"70445": {"name": "...", "email": "..."}}.
  The card shows only what is set; the twin never says a TA's name aloud.
- Answers are Ben's own text, returned as written, with no audio (like the
  logistics referral). Nothing here is generated by a model.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

from . import config

KIND = "faq"
ENTRIES_FILE = Path(__file__).with_name("faq_entries.json")
COURSE_LABELS = {"70445": "70-445", "45884": "45-884"}
CALENDLY = {"label": "Book a 30-minute meeting", "url": "https://calendly.com/bencollierphd"}
_EMAIL = re.compile(r"^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$")


@dataclass(frozen=True)
class Entry:
    id: str
    title: str
    patterns: tuple[re.Pattern[str], ...]
    answers: dict[str, str]
    links: tuple[dict[str, str], ...] = ()
    contact_ta: bool = False

    def courses(self) -> list[str]:
        return list(config.COURSE_CODES) if "all" in self.answers else [c for c in config.COURSE_CODES if c in self.answers]


@dataclass
class Match:
    entry: Entry
    answers: list[dict[str, str]] = field(default_factory=list)  # [{course, course_label, text}]


@lru_cache(maxsize=1)
def entries() -> tuple[Entry, ...]:
    data = json.loads(ENTRIES_FILE.read_text(encoding="utf-8"))
    out = []
    for raw in data["entries"]:
        flags = 0 if raw.get("case_sensitive_patterns") else re.I
        out.append(
            Entry(
                id=raw["id"],
                title=raw["title"],
                patterns=tuple(re.compile(p, flags) for p in raw["patterns"]),
                answers=dict(raw["answers"]),
                links=tuple(raw.get("links") or ()),
                contact_ta=bool(raw.get("contact_ta")),
            )
        )
    return tuple(out)


def _text(question: str) -> str:
    return re.sub(r"\s+", " ", (question or "").replace("’", "'")).strip()


def match(question: str, course: Optional[str]) -> Optional[Match]:
    """The first FAQ entry whose pattern matches and that has an answer for this course filter."""
    text = _text(question)
    for entry in entries():
        if not any(p.search(text) for p in entry.patterns):
            continue
        if "all" in entry.answers:
            return Match(entry, [{"course": course or "", "course_label": COURSE_LABELS.get(course or "", ""),
                                  "text": entry.answers["all"]}])
        wanted = [course] if course else list(config.COURSE_CODES)
        found = [{"course": c, "course_label": COURSE_LABELS[c], "text": entry.answers[c]}
                 for c in wanted if c in entry.answers]
        if found:
            return Match(entry, found)
    return None


def ta_contacts(course: Optional[str]) -> list[dict[str, str]]:
    """TA contact cards for this course filter (both courses for "All courses"), from TA_CONTACTS."""
    raw = config.env("TA_CONTACTS")
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        config.log.warning("TA_CONTACTS is not valid JSON")
        return []
    out = []
    for code in ([course] if course else list(config.COURSE_CODES)):
        info = data.get(code) if isinstance(data, dict) else None
        if not isinstance(info, dict):
            continue
        email = str(info.get("email") or "").strip()
        if not _EMAIL.match(email):
            continue
        out.append({
            "course": code,
            "course_label": COURSE_LABELS.get(code, code),
            "name": str(info.get("name") or "").strip()[:80],
            "email": email,
        })
    return out


def message(m: Match) -> str:
    """One text for the stage: a single answer as is; several labelled by course."""
    if len(m.answers) == 1:
        return m.answers[0]["text"]
    return "\n\n".join(f"For {a['course_label']}: {a['text']}" for a in m.answers)


def reply(question: str, course: Optional[str], m: Match, follow_ups: list[str]) -> dict[str, Any]:
    """The 200 reply for an FAQ hit: Ben's words, link buttons, and TA cards when the answer points to the TA."""
    return {
        "question": question,
        "covered": False,
        "kind": KIND,
        "faq_id": m.entry.id,
        "title": m.entry.title,
        "segments": [],
        "sources": [],
        "message": message(m),
        "answers": m.answers,
        "links": [dict(link) for link in m.entry.links],
        "contacts": ta_contacts(course if course else None) if m.entry.contact_ta else [],
        "follow_ups": follow_ups[:3],
    }
